platform :ios, '8.1'
use_frameworks!
swift_version = "4.2"

source 'https://github.com/twilio/cocoapod-specs'
source 'https://github.com/CocoaPods/Specs.git'

project 'PacifySDKSample.xcodeproj'

target :PacifySDKSample do
project 'PacifySDKSample.xcodeproj'
    pod 'PacifySDK', '= 1.0.2’
    pod 'TwilioVideo', '= 1.3.6'
    
end

post_install do |installer|  
  installer.pods_project.targets.each do |target|
    if ['PromiseKit'].include? "#{target}"
      print "Setting #{target}'s SWIFT_VERSION to 4.0\n"
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
