platform :ios, '8.1'
use_frameworks!
swift_version = "4.2"

source 'https://github.com/twilio/cocoapod-specs'
source 'https://github.com/CocoaPods/Specs.git'

project 'PacifySDKSample.xcodeproj'

target :PacifySDKSample do
project 'PacifySDKSample.xcodeproj'
    pod 'PacifySDK', '= 1.0.1’
    pod 'TwilioVideo', '= 1.3.6'
end
